"""Pipeline Orchestrator – run the full agent pipeline in sequence."""

from __future__ import annotations

import structlog

from reqlens.agents.ambiguity_agent import AmbiguityAgent
from reqlens.agents.base import AgentContext, AgentResult
from reqlens.agents.classification_agent import ClassificationAgent
from reqlens.agents.composer_agent import ComposerAgent
from reqlens.agents.consistency_agent import ConsistencyAgent
from reqlens.agents.dependency_agent import DependencyAgent
from reqlens.agents.elicitation_agent import ElicitationAgent
from reqlens.agents.evidence_agent import EvidenceAgent
from reqlens.agents.extraction_agent import ExtractionAgent
from reqlens.agents.traceability_agent import TraceabilityAgent
from reqlens.domain.enums import (
    DependencyEdgeType,
    EvidenceStatus,
    RequirementStatus,
    ReviewStatus,
)
from reqlens.domain.ids import generate_id
from reqlens.domain.models import Requirement, SourceSpan
from reqlens.storage.graph_store import GraphStore
from reqlens.storage.repositories import (
    ConflictFindingRepository,
    RequirementCandidateRepository,
    RequirementRepository,
    TraceLinkRepository,
)

logger = structlog.get_logger(__name__)


class PipelineOrchestrator:
    """Runs the full requirement engineering pipeline."""

    def __init__(
        self,
        extraction_agent: ExtractionAgent,
        evidence_agent: EvidenceAgent,
        classification_agent: ClassificationAgent,
        ambiguity_agent: AmbiguityAgent,
        dependency_agent: DependencyAgent,
        consistency_agent: ConsistencyAgent,
        traceability_agent: TraceabilityAgent,
        elicitation_agent: ElicitationAgent,
        composer_agent: ComposerAgent,
        graph_store: GraphStore,
        requirement_repo: RequirementRepository,
        candidate_repo: RequirementCandidateRepository,
        conflict_repo: ConflictFindingRepository,
        trace_link_repo: TraceLinkRepository,
    ) -> None:
        self.extraction_agent = extraction_agent
        self.evidence_agent = evidence_agent
        self.classification_agent = classification_agent
        self.ambiguity_agent = ambiguity_agent
        self.dependency_agent = dependency_agent
        self.consistency_agent = consistency_agent
        self.traceability_agent = traceability_agent
        self.elicitation_agent = elicitation_agent
        self.composer_agent = composer_agent
        self.graph_store = graph_store
        self.requirement_repo = requirement_repo
        self.candidate_repo = candidate_repo
        self.conflict_repo = conflict_repo
        self.trace_link_repo = trace_link_repo

    async def run_full_pipeline(
        self,
        context: AgentContext,
        spans: list[SourceSpan],
    ) -> list[AgentResult]:
        """Execute the complete pipeline."""
        results: list[AgentResult] = []

        # Step 1: Extraction
        logger.info("pipeline.step", step="extraction")
        extraction_result = await self.extraction_agent.run(context, spans)
        results.append(extraction_result)

        # run() already persisted candidates — read them from DB to avoid a second LLM call
        candidates = self.candidate_repo.list_by_project(context.project_id)
        questions = []  # open questions not persisted; regenerated by elicitation agent
        if not candidates:
            logger.warning("pipeline.no_candidates")
            return results

        # Step 2: Evidence
        logger.info("pipeline.step", step="evidence")
        # assess_candidates() is the synchronous core; run() just wraps it.
        # Call assess_candidates() once and build AgentResult manually to avoid a double LLM call.
        assessments = self.evidence_agent.assess_candidates(context, candidates)
        evidence_result = AgentResult(
            agent_name=self.evidence_agent.name,
            status="completed",
            created_ids=[a.id for a in assessments],
        )
        results.append(evidence_result)

        # Promote entailed candidates to requirements
        requirements: list[Requirement] = []
        for cand, assessment in zip(candidates, assessments):
            if assessment.status == EvidenceStatus.entailed:
                req = Requirement(
                    id=generate_id("REQ"),
                    project_id=context.project_id,
                    text=cand.text,
                    kind=cand.requirement_kind,
                    nfr_subtype=cand.nfr_subtype,
                    status=RequirementStatus.evidence_checked,
                    created_from_candidate_id=cand.id,
                    source_span_ids=assessment.supporting_span_ids or cand.source_span_ids,
                )
                requirements.append(req)
                # Mirror node into graph
                self.graph_store.upsert_requirement_node(
                    req.id,
                    {"text": req.text, "kind": req.kind.value, "status": req.status.value},
                )
                for span_id in req.source_span_ids:
                    self.graph_store.upsert_edge(
                        req.id, span_id,
                        DependencyEdgeType.derived_from.value,
                        {"confidence": assessment.confidence},
                    )

        if not requirements:
            logger.warning("pipeline.no_evidence_checked_requirements")
            return results

        # Persist requirements to DB
        logger.info("pipeline.persist_requirements", count=len(requirements))
        self.requirement_repo.create_many(requirements)

        # Step 3: Classification
        logger.info("pipeline.step", step="classification")
        classification_result = await self.classification_agent.run(context, requirements)
        results.append(classification_result)

        # Step 4: Ambiguity
        logger.info("pipeline.step", step="ambiguity")
        ambiguity_result = await self.ambiguity_agent.run(context, requirements)
        results.append(ambiguity_result)

        # Capture findings for the elicitation agent (run later, before composer).
        # analyse() is deterministic w.r.t. the LLM call already made by .run(),
        # but the agent does not cache state, so we call it again to get domain
        # objects. The LLM cost is the same shape as one ambiguity call.
        try:
            quality_findings = self.ambiguity_agent.analyse(context, requirements)
        except Exception as exc:
            logger.warning("pipeline.ambiguity_findings_failed", error=str(exc))
            quality_findings = []

        # Step 5: Dependency
        logger.info("pipeline.step", step="dependency")
        dependency_result = await self.dependency_agent.run(context, requirements)
        results.append(dependency_result)

        # Step 6: Consistency – detect conflicts and PERSIST them
        logger.info("pipeline.step", step="consistency")
        consistency_result = await self.consistency_agent.run(context, requirements)
        results.append(consistency_result)

        conflicts = self.consistency_agent.detect_conflicts(context, requirements)
        if conflicts:
            logger.info("pipeline.persist_conflicts", count=len(conflicts))
            try:
                self.conflict_repo.create_many(conflicts)
            except Exception as exc:
                logger.warning("pipeline.persist_conflicts_failed", error=str(exc))

        # Step 7: Traceability – build trace links and PERSIST them
        # build_trace_links() is called once inside run(); we call it again here
        # directly so we have the domain objects for persistence without a
        # second LLM round-trip (the method is deterministic for source links
        # and the LLM branch is only reached when test_artifacts are supplied).
        logger.info("pipeline.step", step="traceability")
        trace_links = self.traceability_agent.build_trace_links(context, requirements, spans)
        traceability_result = await self.traceability_agent.run(context, requirements, spans)
        results.append(traceability_result)

        if trace_links:
            logger.info("pipeline.persist_trace_links", count=len(trace_links))
            try:
                self.trace_link_repo.create_many(trace_links)
            except Exception as exc:
                logger.warning("pipeline.persist_trace_links_failed", error=str(exc))

        # Step 8: Mark requirements as accepted in RequirementRepository.
        # The graph store is intentionally NOT updated here — graph nodes are
        # only synced when the user clicks "Sync Knowledge Graph decision",
        # which calls POST /review-decisions → sync_requirement_decision().
        logger.info("pipeline.update_statuses", count=len(requirements))
        for req in requirements:
            req.review_status = ReviewStatus.accepted
            req.status = RequirementStatus.accepted
            self.requirement_repo.update(req)

        # Step 9: Elicitation – turn the extractor's unresolved questions
        # (and any ambiguity findings) into clear stakeholder-facing questions
        # so the SRS's "Open Questions" section is actionable instead of raw.
        logger.info("pipeline.step", step="elicitation")
        elicitation_result = await self.elicitation_agent.run(
            context,
            open_questions=questions,
            insufficient_requirements=None,
            quality_findings=quality_findings,
        )
        results.append(elicitation_result)

        try:
            stakeholder_questions = self.elicitation_agent.generate_questions(
                context,
                open_questions=questions,
                insufficient_requirements=None,
                quality_findings=quality_findings,
            )
        except Exception as exc:
            logger.warning("pipeline.elicitation_failed", error=str(exc))
            stakeholder_questions = questions  # fallback: raw extractor questions

        # Mirror the per-step elicitation endpoint and cache the result so the
        # Composer step can find it under the same key regardless of code path.
        try:
            from reqlens.services.srs_cache import save_stakeholder_questions
            save_stakeholder_questions(context.project_id, stakeholder_questions)
        except Exception as exc:
            logger.warning("pipeline.questions_cache_failed", error=str(exc))

        # Step 10: Composer – build and cache the SRS, with the elicitation
        # agent's stakeholder questions as the Open Questions section.
        logger.info("pipeline.step", step="composer")
        srs_output = self.composer_agent.compose_srs(
            context, requirements,
            conflicts=conflicts,
            open_questions=stakeholder_questions,
        )
        try:
            from reqlens.services.srs_cache import save_srs_markdown
            markdown = self.composer_agent.srs_to_markdown(srs_output)
            save_srs_markdown(context.project_id, markdown)
        except Exception as exc:
            logger.warning("pipeline.srs_cache_failed", error=str(exc))

        composer_result = AgentResult(
            agent_name=self.composer_agent.name,
            status="completed",
        )
        results.append(composer_result)

        logger.info(
            "pipeline.complete",
            total_steps=len(results),
            requirements=len(requirements),
            conflicts=len(conflicts),
            trace_links=len(trace_links),
        )
        return results
